version: "3.8"

services:
  scheduler:
    container_name: scheduler
    build:
      context: scheduler-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: always
    networks:
      - backend

  user-management:
    container_name: user-management
    build:
      context: user-management
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    restart: always
    depends_on:
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/user_db
      SPRING_DATASOURCE_USERNAME: $USER_ACCOUNT_DB_USERNAME
      SPRING_DATASOURCE_PASSWORD: $USER_ACCOUNT_DB_PASSWORD
    networks:
      - backend

  drone-management:
    container_name: drone-management
    build:
      context: drone-management
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    restart: always
    depends_on:
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/drone_db
      SPRING_DATASOURCE_USERNAME: $DRONE_DB_USERNAME
      SPRING_DATASOURCE_PASSWORD: $DRONE_DB_PASSWORD
    networks:
      - backend

  third-party-transportation:
    container_name: third-party-transportation
    build:
      context: third-party-transportation-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb/third_party_transportation_db
    networks:
      - backend

  package-management:
    container_name: package-management
    build:
      context: package-management
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb/package_db
    networks:
      - backend

  delivery-management:
    container_name: delivery-management
    build:
      context: delivery-management
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb/delivery_db
    networks:
      - backend

  mysqldb:
    container_name: mysqldb
    build:
      context: database/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  mongodb:
    container_name: mongodb
    build:
      context: database/mongodb
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    restart: always
    networks:
      - backend

networks:
  backend:
