const REQUEST_STATUS_WAITING = "WAITING";
const REQUEST_STATUS_CANCELED = "CANCELED";
const REQUEST_STATUS_COMPLETED = "COMPLETED";

const RequestStatus = [
  REQUEST_STATUS_WAITING,
  REQUEST_STATUS_CANCELED,
  REQUEST_STATUS_COMPLETED,
];

module.exports = {
  RequestStatus,
};
