const DELIVERY_STATUS_CREATED = "CREATED";
const DELIVERY_STATUS_CANCELED = "CANCELED";
const DELIVERY_STATUS_HEADED_TO_DROP_OFF = "HEADED_TO_DROP_OFF";
const DELIVERY_STATUS_COMPLETED = "COMPLETED";

export const DeliveryStatus = {
  DELIVERY_STATUS_CREATED,
  DELIVERY_STATUS_CANCELED,
  DELIVERY_STATUS_HEADED_TO_DROP_OFF,
  DELIVERY_STATUS_COMPLETED,
};
